package codeyourbrand.javainterview.common.model;

import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
public enum ApplicationErrorCode {
    GENERIC_CLIENT_ERROR(100, HttpStatus.BAD_REQUEST),
    RESOURCE_NOT_FOUND(153, HttpStatus.NOT_FOUND),
    EXCHANGE_RATE_CHANGED(101, HttpStatus.CONFLICT),
    COUPON_EXPIRED(102, HttpStatus.BAD_REQUEST),
    COUPON_INSUFFICIENT_USAGES(103, HttpStatus.BAD_REQUEST),
    COUPON_INVALID_RESERVATIONS(104, HttpStatus.BAD_REQUEST),
    RESERVATION_NOT_ENOUGH_SLOTS(105, HttpStatus.BAD_REQUEST),
    RESERVATION_DATETIME_INVALID(106, HttpStatus.BAD_REQUEST),
    RESERVATION_TOTAL_PARTICIPANTS_INVALID(107, HttpStatus.BAD_REQUEST),
    TOUR_NOT_ENOUGH_PLACES(108, HttpStatus.BAD_REQUEST),
    TOUR_FEATURE_NOT_AVAILABLE(109, HttpStatus.BAD_REQUEST),
    PICKUP_LOCATION_NOT_AVAILABLE(110, HttpStatus.BAD_REQUEST),
    TOUR_NEW_MAX_PARTICIPANTS_TOO_SMALL(111, HttpStatus.BAD_REQUEST),
    TOUR_IS_NOT_PLANNED(112, HttpStatus.BAD_REQUEST),
    GUIDE_AVAILABILITY_NOT_ENABLED(113, HttpStatus.BAD_REQUEST),
    PROVIDED_GREATER_THAN_ONE_AMOUNT_OF_SINGLE_EXTRA_OPTION(114, HttpStatus.BAD_REQUEST),
    APARTMENT_NOT_AVAILABLE(115, HttpStatus.CONFLICT),
    APARTMENT_ACCOMMODATIONS_AMOUNT_NOT_VALID(116, HttpStatus.BAD_REQUEST),
    APARTMENT_PEOPLE_AMOUNT_TOO_HIGH(117, HttpStatus.BAD_REQUEST),
    ATTRACTION_INACTIVE(118, HttpStatus.BAD_REQUEST),
    TOUR_TIME_REQUIRED(119, HttpStatus.BAD_REQUEST),
    NATIVE_DRIVER_AVAILABILITY_NOT_ENABLED(120, HttpStatus.BAD_REQUEST),
    PRIVATE_GUIDE_NOT_AVAILABLE(121, HttpStatus.CONFLICT),
    NATIVE_DRIVER_NOT_AVAILABLE(122, HttpStatus.CONFLICT),
    EXTRA_OPTION_NOT_AVAILABLE(123, HttpStatus.BAD_REQUEST),
    RESERVATION_INVALID_ADDITIONAL_DETAILS_FORMAT(124, HttpStatus.BAD_REQUEST),
    ATTRACTION_VARIANT_NOT_AVAILABLE(125, HttpStatus.BAD_REQUEST),
    AVAILABILITY_EXTERNAL_ENABLED(126, HttpStatus.CONFLICT),
    DATA_VALIDATION_ERROR(127, HttpStatus.BAD_REQUEST),
    CURRENCY_NOT_SUPPORTED(128, HttpStatus.BAD_REQUEST),
    EXTRA_OPTIONS_FROM_SAME_GROUP(129, HttpStatus.BAD_REQUEST),
    INVALID_GEOLOCATION(130, HttpStatus.BAD_REQUEST),
    TOUR_PARTICIPANTS_NOT_PROVIDED(131, HttpStatus.BAD_REQUEST),
    TOUR_PARTICIPANTS_BELONG_TO_DIFFERENT_TOURS(132, HttpStatus.BAD_REQUEST),
    CANNOT_UPDATE_TOUR_TERM(133, HttpStatus.BAD_REQUEST),
    UNAUTHORIZED(134, HttpStatus.UNAUTHORIZED),
    FORBIDDEN(135, HttpStatus.FORBIDDEN),
    COUPON_ALREADY_EXISTS(136, HttpStatus.CONFLICT),
    COUPON_NOT_FOUND(137, HttpStatus.BAD_REQUEST),
    TRAVEL_AGENCY_INSUFFICIENT_BALANCE(138, HttpStatus.PAYMENT_REQUIRED),
    INVALID_COMMISSION_VALUE(139, HttpStatus.BAD_REQUEST),
    COUPON_NOT_APPLICABLE_FOR_TRAVEL_AGENCY(140, HttpStatus.BAD_REQUEST),
    USER_WITH_GIVEN_LOGIN_ALREADY_EXISTS(141, HttpStatus.CONFLICT),
    TRAVEL_AGENCY_CURRENCY_NOT_SUPPORTED(142, HttpStatus.BAD_REQUEST),
    OBSOLETE_EXTRA_OPTION(143, HttpStatus.BAD_REQUEST),
    OBSOLETE_AGE_GROUP(144, HttpStatus.BAD_REQUEST),
    TICKET_ALREADY_EXISTS(145, HttpStatus.CONFLICT),
    REQUESTED_TICKETS_ARE_NOT_UNIQUE(146, HttpStatus.BAD_REQUEST),
    NOT_ENOUGH_TICKETS_AVAILABLE(147, HttpStatus.INTERNAL_SERVER_ERROR),
    AGENT_INSUFFICIENT_BALANCE(148, HttpStatus.PAYMENT_REQUIRED),
    APARTMENT_NOT_AVAILABLE_FOR_GIVEN_DATES(149, HttpStatus.CONFLICT),
    COUPON_NOT_APPLICABLE_FOR_APARTMENT(150, HttpStatus.BAD_REQUEST),
    COUPON_MINIMUM_STAY_AMOUNT_REQUIREMENT_NOT_MET(151, HttpStatus.BAD_REQUEST),
    COUPON_NOT_ALLOWED_WITHIN_GIVEN_PERIOD(152, HttpStatus.BAD_REQUEST),
    APARTMENT_MINIMUM_STAY_REQUIREMENT_NOT_MET(153, HttpStatus.BAD_REQUEST),
    APARTMENT_MAXIMUM_STAY_REQUIREMENT_NOT_MET(154, HttpStatus.BAD_REQUEST),
    RESERVATION_NOT_AVAILABLE(155, HttpStatus.BAD_REQUEST),
    IP_ADDRESS_IS_BLACKLISTED(156, HttpStatus.BAD_REQUEST),
    IP_ADDRESS_ALREADY_HAS_ENTRY_IN_BLACKLIST(157, HttpStatus.CONFLICT),
    GUESTS_AMOUNT_NOT_MATCHING_PARTICIPANTS(158, HttpStatus.BAD_REQUEST),
    TOUR_IS_UNDERSTAFFED(159, HttpStatus.BAD_REQUEST),
    WORKER_UNAVAILABLE(160, HttpStatus.BAD_REQUEST),
    WORKER_ROLE_UNSUPPORTED_FOR_TOUR_TYPE(161, HttpStatus.BAD_REQUEST),
    INVALID_TOUR_ORGANIZATION(162, HttpStatus.BAD_REQUEST),
    NOT_ENOUGH_SPOTS_IN_TOUR(163, HttpStatus.BAD_REQUEST),
    TOUR_TIME_NOT_EDITABLE(164, HttpStatus.BAD_REQUEST),
    PARTICIPANTS_GROUP_ALREADY_BELONGS_TO_TOUR(165, HttpStatus.BAD_REQUEST),
    PARTICIPANTS_GROUPS_DOES_NOT_BELONG_TO_SAME_TOUR_BLOCK(166, HttpStatus.BAD_REQUEST),
    PARTICIPANTS_GROUPS_DOES_NOT_BELONG_TO_SAME_TOUR(167, HttpStatus.BAD_REQUEST),
    PARTICIPANTS_GROUPS_INVALID_SPLITTING_INDEX(168, HttpStatus.BAD_REQUEST),
    PARTICIPANTS_GROUPS_CRITICAL_DATA_MISMATCH(169, HttpStatus.BAD_REQUEST),
    PARTICIPANTS_GROUPS_EXTRAS_NOT_ALLOWED_FOR_NON_ADULT_GROUP(170, HttpStatus.BAD_REQUEST),
    GENERIC_SERVER_ERROR(500, HttpStatus.INTERNAL_SERVER_ERROR);

    private final int id;
    private final String code;
    private final HttpStatus httpStatus;

    ApplicationErrorCode(int id, HttpStatus httpStatus) {
        this.id = id;
        this.code = name();
        this.httpStatus = httpStatus;
    }

    @Override
    public String toString() {
        return String.format("%s(%d)", code, id);
    }
}
